import { jsx as _jsx, jsxs as _jsxs } from "nojsx/jsx-runtime";
/** @jsxImportSource nojsx */
import { NComponent } from "nojsx/core/components/components";
import { Card } from "../components/card";
import { StatCounter } from "../components/stat-counter";
export class HomePage extends NComponent {
    constructor(props) {
        super("HomePage", props);
    }
    html = () => (_jsxs("div", { class: "page-enter", children: [_jsxs("section", { class: "relative overflow-hidden rounded-2xl bg-gradient-to-br from-amber-50 via-orange-50 to-rose-50 px-6 py-16 text-center md:py-24", children: [_jsx("div", { class: "pointer-events-none absolute -right-16 -top-16 h-64 w-64 rounded-full bg-amber-200/40 blur-3xl" }), _jsx("div", { class: "pointer-events-none absolute -bottom-20 -left-20 h-72 w-72 rounded-full bg-orange-200/30 blur-3xl" }), _jsx("p", { class: "relative text-sm font-bold uppercase tracking-[0.25em] text-amber-700", children: "Built with nojsx" }), _jsxs("h1", { class: "relative mt-3 text-4xl font-black leading-tight text-stone-900 md:text-6xl", children: ["Class-based.", _jsx("br", {}), "Client-rendered.", _jsx("br", {}), "No ceremony."] }), _jsx("p", { class: "relative mx-auto mt-5 max-w-lg text-lg text-stone-600", children: "A TypeScript-first JSX runtime for browser UI -- components render and update with minimal glue work." })] }), _jsxs("section", { class: "mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3", children: [_jsx(Card, { id: this.id + "1", title: "JSX Runtime", subtitle: "Custom jsx-runtime", accent: "amber", children: _jsx("p", { class: "text-sm text-stone-600", children: "Not React. Not virtual DOM. nojsx compiles TSX to HTML strings and patches the real DOM directly." }) }), _jsx(Card, { id: this.id + "2", title: "NComponent", subtitle: "Class-based state", accent: "orange", children: _jsxs("p", { class: "text-sm text-stone-600", children: ["State lives on the instance. Call ", _jsx("code", { class: "rounded bg-stone-100 px-1 text-xs", children: "this.render()" }), " to re-render -- no hooks, no reconciler."] }) }), _jsx(Card, { id: this.id + "3", title: "Client Routing", subtitle: "NavOutlet + getShell().nav()", accent: "rose", children: _jsx("p", { class: "text-sm text-stone-600", children: "Register page routes on the client. NavOutlet swaps pages. History API updates the URL." }) })] }), _jsxs("section", { class: "mt-12", children: [_jsx("h2", { class: "text-center text-xl font-bold text-stone-800", children: "Interactive State" }), _jsx("p", { class: "mt-2 text-center text-sm text-stone-500", children: "Each counter is an independent NComponent instance with its own state." }), _jsxs("div", { class: "mt-6 grid gap-5 sm:grid-cols-3", children: [_jsx(StatCounter, { id: "1", label: "Alpha", initial: 0, step: 1 }), _jsx(StatCounter, { id: "2", label: "Beta", initial: 100, step: 10 }), _jsx(StatCounter, { id: "3", label: "Gamma", initial: 50, step: 5 })] })] })] }));
}
