#!/usr/bin/env bun
import path from "node:path";
import process from "node:process";
import { readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

type CliOptions = {
	pagesRoot: string;
	outFile: string;
};

type PageModule = {
	importPath: string;
	exportName: string;
	baseExportName: string;
	routePath: string;
};

function parseArgs(argv: string[]): CliOptions {
	let pagesRoot = "";
	let outFile = "";

	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i];
		if (arg === "--pages-root") {
			pagesRoot = argv[++i] ?? "";
			continue;
		}
		if (arg === "--out") {
			outFile = argv[++i] ?? "";
			continue;
		}
	}

	if (!pagesRoot || !outFile) {
		console.error("[nojsx] usage: nojsx-generate-component-loaders --pages-root <path> --out <file>");
		process.exit(1);
	}

	return {
		pagesRoot: path.resolve(process.cwd(), pagesRoot),
		outFile: path.resolve(process.cwd(), outFile),
	};
}

function toRoutePath(exportName: string): string {
	const trimmed = exportName.replace(/Page$/, "") || exportName;
	const kebab = trimmed
		.replace(/([a-z0-9])([A-Z])/g, "$1-$2")
		.replace(/\s+/g, "-")
		.toLowerCase();

	if (kebab === "home") return "/home";
	return `/${kebab}`;
}

async function readPageModules(pagesRoot: string, outFile: string): Promise<PageModule[]> {
	if (!existsSync(pagesRoot)) {
		throw new Error(`pages root does not exist: ${pagesRoot}`);
	}

	const entries = await readdir(pagesRoot, { withFileTypes: true });
	const files = entries
		.filter((entry) => entry.isFile() && /\.(tsx|ts)$/i.test(entry.name))
		.map((entry) => entry.name)
		.sort((a, b) => a.localeCompare(b));

	const modules: PageModule[] = [];
	for (const fileName of files) {
		const baseName = fileName.replace(/\.(tsx|ts)$/i, "");
		const exportName = `${baseName.charAt(0).toUpperCase()}${baseName.slice(1)}Page`;
		const sourcePath = path.join(pagesRoot, fileName);
		const relImport = path.relative(path.dirname(outFile), sourcePath).replace(/\\/g, "/").replace(/\.(tsx|ts)$/i, "");
		const importPath = relImport.startsWith(".") ? relImport : `./${relImport}`;
		modules.push({
			importPath,
			exportName,
			baseExportName: `${baseName.charAt(0).toUpperCase()}${baseName.slice(1)}`,
			routePath: toRoutePath(exportName),
		});
	}

	return modules;
}

function createOutput(modules: PageModule[]): string {
	const importLines = modules.map((mod, index) => `import * as M${index} from ${JSON.stringify(mod.importPath)};`);
	const loaderLines = modules.map((mod, index) => {
		const lines = [
			`if (M${index} && (M${index} as any)[${JSON.stringify(mod.exportName)}]) {`,
			`\tnojsxComponentLoaders[${JSON.stringify(mod.exportName)}] = (props?: any) => new ((M${index} as any)[${JSON.stringify(mod.exportName)}])(props);`,
		];
		if (mod.baseExportName !== mod.exportName) {
			lines.push(`\tnojsxComponentLoaders[${JSON.stringify(mod.baseExportName)}] = (props?: any) => new ((M${index} as any)[${JSON.stringify(mod.exportName)}])(props);`);
		}
		lines.push(`}`);
		return lines.join("\n");
	});
	const routeLines = modules.map((mod) => `\t${JSON.stringify(mod.routePath)}: { componentName: ${JSON.stringify(mod.exportName)} },`);
	const pageMapLines = modules.map((mod) => `\t${JSON.stringify(mod.exportName)}: ${JSON.stringify(mod.routePath)},`);

	return [
		"// AUTO-GENERATED by nojsx-generate-component-loaders. DO NOT EDIT.",
		"// Usage: nojsx-generate-component-loaders --pages-root <path> --out <file>",
		"import { nojsxComponentLoaders } from \"nojsx\";",
		...importLines,
		"",
		"const __g = globalThis as any;",
		"",
		...loaderLines,
		"",
		"export type NojsxPageRouteEntry = { componentName: string };",
		"export const nojsxPageRoutes: Record<string, NojsxPageRouteEntry> = {",
		...routeLines,
		"};",
		"__g.__nojsxPageRoutes = nojsxPageRoutes;",
		"",
		"export const nojsxPages = {",
		...pageMapLines,
		"} as const;",
		"__g.__nojsxPages = nojsxPages;",
		"",
	].join("\n");
}

async function main() {
	const options = parseArgs(process.argv.slice(2));
	const modules = await readPageModules(options.pagesRoot, options.outFile);
	if (modules.length === 0) {
		throw new Error(`no page modules found in ${options.pagesRoot}`);
	}
	await writeFile(options.outFile, createOutput(modules), "utf8");
	console.log(`[nojsx] generated ${path.relative(process.cwd(), options.outFile).replace(/\\/g, "/")}`);
}

void main().catch((error) => {
	console.error(error?.stack || error?.message || error);
	process.exit(1);
});
